version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-v0.1.2
      dockerfile: Dockerfile
    container_name: rag-llm-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-llm-backend
    volumes:
      - ./backend/.env:/app/.env:ro
    env_file:
      - ./backend/.env
    environment:
      - TZ=UTC
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 